# Generated by Django 4.2.7 on 2025-08-04 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='worker',
            new_name='volunteer',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_applications', to='accounts.user'),
        ),
    ]
