# Generated by Django 4.2.7 on 2025-08-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20250804_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='call_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='enable_call',
            field=models.BooleanField(default=True, help_text='Allow phone calls'),
        ),
        migrations.AddField(
            model_name='job',
            name='enable_whatsapp',
            field=models.BooleanField(default=True, help_text='Allow WhatsApp contact'),
        ),
        migrations.AddField(
            model_name='job',
            name='event_duration_days',
            field=models.PositiveIntegerField(default=1, help_text='Number of days the event takes place'),
        ),
        migrations.AddField(
            model_name='job',
            name='event_end_date',
            field=models.DateField(blank=True, help_text='For multi-day events', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Google Maps location URL'),
        ),
        migrations.AddField(
            model_name='job',
            name='venue_name',
            field=models.CharField(blank=True, help_text='Hotel/venue name', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='whatsapp_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number (can be different from contact phone)', max_length=17),
        ),
    ]
