# Generated by Django 4.2.7 on 2025-08-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('manager', 'Manpower/Event Manager'), ('admin', 'Admin')], default='volunteer', max_length=10),
        ),
    ]
