# Generated by Django 4.2.7 on 2025-08-04 17:12

from django.db import migrations, models


def convert_managers_to_volunteers(apps, schema_editor):
    """Convert all managers to volunteers"""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='manager').update(role='volunteer')


def reverse_conversion(apps, schema_editor):
    """Reverse conversion - this is not perfect but better than nothing"""
    pass  # We can't perfectly reverse this, but that's okay


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(convert_managers_to_volunteers, reverse_conversion),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('admin', 'Admin')], default='volunteer', max_length=10),
        ),
    ]
