# Generated by Django 4.2.7 on 2025-08-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_convert_managers_to_volunteers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Overall verification status'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_details',
            field=models.TextField(blank=True, help_text='Details about verification'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_type',
            field=models.CharField(blank=True, choices=[('government_id', 'Government ID'), ('business_license', 'Business License'), ('email_verified', 'Email Verified'), ('phone_verified', 'Phone Verified'), ('manual_review', 'Manual Review')], max_length=50),
        ),
    ]
